//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSoccerPoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Jugador
    {
        public int jug_codigo { get; set; }
        [DisplayName("Equipo")]
        [Required]
        public Nullable<int> equ_codigo { get; set; }
        [DisplayName("Posición")]
        [Required]
        public string pos_codigo { get; set; }
        [DisplayName("Nombre")]
        [Required]
        public string jug_nombre { get; set; }
        [DisplayName("Primer Apellido")]
        [Required]
        public string jug_primerApellido { get; set; }
        [DisplayName("Segundo Apellido")]

        public string jug_segundoApellido { get; set; }
        [DisplayName("Fecha nacimiento")]
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> jug_fechaNacimiento { get; set; }

        public virtual Equipo Equipo { get; set; }
        public virtual Posicion Posicion { get; set; }
    }
}
