//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSoccerPoo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Partido
    {
        public int par_codigo { get; set; }
        [DisplayName("Equipo visitante")]
        [Required]
        public Nullable<int> equ_codigo_visitante { get; set; }
        [DisplayName("Equipo Local")]
        [Required]
        public Nullable<int> equ_codigo_local { get; set; }
        [DisplayName("Torneo")]
        [Required]
        public Nullable<int> tor_codigo { get; set; }
        [DisplayName("Fecha")]
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> par_fecha { get; set; }
        [DisplayName("Hora Inicio")]
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.TimeSpan> par_horaInicio { get; set; }
        [DisplayName("Hora fin")]
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.TimeSpan> par_horaFin { get; set; }
        [DisplayName("Goles local")]
        [Required]
        public Nullable<int> par_golesLocal { get; set; }
        [DisplayName("Goles visitante")]
        [Required]
        public Nullable<int> par_golesVisitante { get; set; }

        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
